### ISSUE TITLE
InputActionWidget disappears when running as standalone or packages

### ISSUE THREAD

**Issue by edwardteach42** [NanceDevDiaries/PauseMenu#1]
Wondering if you ran into this issue.  The input action widget shows when running in PIE, but does not appear when running as standalone or packaged build.

**Comment by NanceDevDiaries** [comment]
Fixed in [b686dc3b5336b1647e4d031a7183529984a6409b](https://github.com/NanceDevDiaries/PauseMenu/commit/b686dc3b5336b1647e4d031a7183529984a6409b)
